### ISSUE TITLE
Bounds error if starCount too high

### ISSUE THREAD

**Issue by andymikulski** [as2d/as2d-example#7]
Steps to reproduce:

1) Clone
2) Change `starCount` from `3000` to `7500`
3) Re-run and observe a few steps will tick through until these errors are shown:
```
Error: not a string: 0 index.js:134
RuntimeError: index out of bounds
```

![as2d-overflow](https://user-images.githubusercontent.com/2767162/73186551-ec0e2c00-40ed-11ea-87ec-8317e7a3f358.gif)

----

Additionally,

4) Change these lines:
```
for (let i = 0; i < starCount; i++) {
  index = i << 1;
```
to:
```
for (let index = 0; index < starCount; index += 2) {
```
5) Change `starCount` to `10000`, and re-run. You'll find there are no errors and it runs fine.
6) Change `starCount` to anything over 10000 and re-run. You'll find the above out of bounds error will come up again.

---

Not sure if this is an issue with as2d, AssemblyScript, or something else entirely.

**Comment by andymikulski** [comment]
From #6, after updating AssemblyScript to `0.9.0`, the `starCount` can be pushed up to `15000` before breaking (with above `index += 2` change). This leads me to believe the issue is with AssemblyScript, and not as2d. Does that seem accurate?

**Comment by jtenner** [comment]
This might be the case. AssemblyScript is effectively still very experimental software. Also, `as2d` is quite an experiment itself so there could be many things wrong with this example. 🙂 

I'll try to figure out the integer overflow error first and then return to this.

**Comment by jtenner** [comment]
Okay. So one of the secrets about `as2d` is that it doesn't call the functions externally directly until you call `.commit()`. Each function call to the canvas context either changes the state of the context or writes a bunch of values to a buffer. The `commit()` function sends up that buffer pointer and the glue code calls each canvas function in succession, careful to maintain the state of the canvas. If perhaps there are too many stars to draw, a `.comm()` function call mid loop might be helpful to prevent a buffer overflow which would cause this issue.

```ts
if (i % 1000 === 0) ctx.commit();
```

Another thing I notice about this issue is that it always starts with an error during initialization, (which means that buffer pointer might be bad in the first place.) This might cause the out of bounds error as described.

Try fixing #6 first before attempting to debug this, since I believe this is the same error as #6, only with extra error output.

**Comment by jtenner** [comment]
Last thing to note. It's probably way more efficient to generate a single image from a canvas context and draw that instead of drawing 15000 circles each frame. So hypothetically speaking, increasing the circle count here is a bit of a problem regardless.

**Comment by jtenner** [comment]
Please check out #8 and try out that fork. Let me know if you run into any more issues. 🙂
